from sqlalchemy import select
from . import models as m


def img(key: str, *_) -> str:
    # Local illustrations from frontend/public/images (generated by tools/make_images.py)
    return f"/images/{key}.svg"


def empty(db, model) -> bool:
    return db.scalar(select(model.id).limit(1)) is None


def seed(db):
    if empty(db, m.Plan):
        db.add_all([
            m.Plan(name="Floor", price=29, features="Gym floor access\nLocker room\nOpen 5am to 11pm"),
            m.Plan(name="Floor + Classes", price=49, features="Everything in Floor\nUnlimited class bookings\nFree fitness assessment"),
            m.Plan(name="Coached", price=89, features="Everything in Floor + Classes\n2 personal sessions a month\nCustom training plan"),
        ])
    if empty(db, m.Trainer):
        t = [
            m.Trainer(name="Marta Keller", specialty="Strength & powerlifting", bio="Ten years coaching barbell lifts, from first squat to first meet.", image=img("person1", 11, 600, 700)),
            m.Trainer(name="Dev Anand", specialty="Conditioning & HIIT", bio="Builds sessions that are hard for the right reasons. Former 800m runner.", image=img("person2", 12, 600, 700)),
            m.Trainer(name="Lucía Ortega", specialty="Mobility & yoga", bio="Physio-trained. Helps lifters move better and sit at a desk without pain.", image=img("person3", 13, 600, 700)),
            m.Trainer(name="Sam Okafor", specialty="Boxing & footwork", bio="Amateur boxer turned coach. Teaches technique first, speed second.", image=img("person4", 14, 600, 700)),
        ]
        db.add_all(t)
        db.flush()
        rows = [
            ("Barbell Basics", "Squat, bench, deadlift technique in small groups.", "Mon", "18:00", 12, 0, "barbell"),
            ("Morning HIIT", "40 minutes of intervals. Bring a towel.", "Mon", "06:30", 16, 1, "hiit"),
            ("Boxing Fundamentals", "Stance, jab-cross, footwork, bag work.", "Tue", "18:00", 14, 3, "glove"),
            ("Mobility Flow", "Hips, shoulders and spine. All levels.", "Tue", "19:00", 15, 2, "yoga"),
            ("Strength Circuit", "Rotating stations, coached pace.", "Wed", "18:30", 14, 0, "kettlebell"),
            ("Morning HIIT", "40 minutes of intervals. Bring a towel.", "Thu", "06:30", 16, 1, "hiit"),
            ("Boxing Sparring Lite", "Controlled partner drills. Gloves provided.", "Thu", "19:00", 12, 3, "glove2"),
            ("Powerlifting Club", "Programmed heavy work with spotters.", "Fri", "17:30", 10, 0, "barbell2"),
            ("Saturday Engine", "Long conditioning session, partner work.", "Sat", "09:00", 20, 1, "rig"),
            ("Slow Yoga", "Long holds, lots of breathing.", "Sun", "10:00", 15, 2, "yoga2"),
        ]
        for i, (title, desc, day, start, cap, ti, tags) in enumerate(rows):
            db.add(m.GymClass(title=title, description=desc, day=day, start=start, capacity=cap,
                              trainer_id=t[ti].id, image=img(tags, 30 + i)))
    if empty(db, m.Product):
        P = [
            ("Whey Protein 1kg", "Supplements", "Chocolate whey, 25g protein per scoop.", 34.90, 40, "tub"),
            ("Creatine Monohydrate 300g", "Supplements", "Unflavoured, 60 servings.", 19.90, 60, "tub2"),
            ("Pre-Workout Citrus", "Supplements", "Caffeine and citrulline, 30 servings.", 27.50, 35, "bottle"),
            ("Electrolyte Mix", "Supplements", "Sugar-free hydration sachets, box of 20.", 14.00, 80, "bottle2"),
            ("Lifting Straps", "Gear", "Cotton straps for heavy pulls.", 12.00, 50, "straps"),
            ("Weightlifting Belt", "Gear", "10mm leather belt, lever buckle.", 69.00, 15, "belt"),
            ("Adjustable Dumbbell 20kg", "Gear", "Quick-change plates for home training.", 89.00, 12, "dumbbell"),
            ("Resistance Band Set", "Gear", "Five bands, light to heavy.", 22.00, 45, "bands"),
            ("Iron Yard Tee", "Apparel", "Heavy cotton tee, boxy fit.", 26.00, 70, "shirt"),
            ("Training Hoodie", "Apparel", "Brushed fleece, kangaroo pocket.", 58.00, 30, "hoodie"),
            ("Gym Duffel 35L", "Apparel", "Separate shoe compartment.", 45.00, 25, "bag"),
            ("Shaker Bottle 700ml", "Gear", "Leak-proof, with mixing ball.", 9.00, 100, "bottle3"),
        ]
        for i, (n, c, d, pr, st, tags) in enumerate(P):
            db.add(m.Product(name=n, category=c, description=d, price=pr, stock=st, image=img(tags, 50 + i, 600, 600)))
    if empty(db, m.Facility):
        F = [
            ("Strength floor", "Six racks, two platforms, plates to 300kg.", "barbell3"),
            ("Cardio deck", "Rowers, bikes, treadmills and ski-ergs.", "cardio"),
            ("Group studio", "Sprung floor and mirrors for classes.", "studio"),
            ("Recovery room", "Sauna, cold plunge, and foam-rolling area.", "sauna"),
            ("Functional rig", "Sleds, ropes, rings and turf lane.", "rig2"),
            ("Locker rooms", "Showers, day lockers and hair dryers.", "locker"),
        ]
        for i, (n, d, tags) in enumerate(F):
            db.add(m.Facility(name=n, description=d, image=img(tags, 70 + i)))
    if empty(db, m.Testimonial):
        db.add_all([
            m.Testimonial(name="Priya N.", detail="Member for 2 years", quote="I finally deadlift more than I weigh, and nobody rushed me getting there.", image=img("avatar1", 90, 200, 200)),
            m.Testimonial(name="Tomás R.", detail="Coached plan", quote="Marta rebuilt my squat from scratch. My knees stopped hurting in six weeks.", image=img("avatar2", 91, 200, 200)),
            m.Testimonial(name="Hannah B.", detail="Class regular", quote="Morning HIIT is the only reason I am up at six. Small groups make the difference.", image=img("avatar3", 92, 200, 200)),
        ])
    db.commit()
